branches:
  only:
    - master
    - docs
    - ci
sudo : required

language: generic

services:
  - docker

stages:
  - name: validate
    if: branch IN (master, ci)
  - name: build-docs
    if: branch = docs

jobs:
  include:
    - stage: validate
      before_script:
        - docker build -t usnistgov/oscal:dev .
      script:
        - docker run usnistgov/oscal:dev /bin/sh -c "xmllint --noout --schema schema/xml/XSD/oscal-profile-interim.xsd examples/FedRAMP/FedRAMP-HIGH-crude.xml"
