version: '3.3'

services:
  docs:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=production
    volumes:
      - "./:/app"
